################################################################################################################
# Site settings                                                                                             #
################################################################################################################
remote_theme: hydecorp/hydejack@v9.0.5

################################################################################################################
# General settings                                                                                             #
################################################################################################################

lang: pt-BR
title: Magento 2 Expert Developer Study Guide
short_title: Magento 2 Expert Developer
description: Minhas anotações de estudo para a certificação “Adobe Certified Expert Magento Commerce Developer (AD0-E703)”.
tagline: Minhas anotações de estudo para a certificação “Adobe Certified Professional Magento Commerce Developer (AD0-E703)”.
keywords: [
  'Magento',
  'Magento 2',
  'certificação',
  'Adobe',
  'e-commerce',
  'developer'
  ]
  
author:
  # Used by `jekyll-feed`:
  name: Ligia Salzano
  email: ligiasalzano@gmail.com
  # # Used by `jekyll-seo-tag`:
  twitter: ligiasalzano
  github: ligiasalzano
  telegram: ligiasalzano
  instagram: ligiasalzano
  linkedin: ligiasalzano

share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  
# Add links to the sidebar
menu:
  - title: 01 - Arquitetura Magento e técnicas de customização
    url:   /arquitetura-e-customizacao
  - title: 02 - Processamento do fluxo de requisição
    url:   /processamento-do-fluxo-de-requisicao
  - title: 03 - Personalizando a Interface de Usuário (UI) do Magento
    url:   /personalizando-a-ui
  - title: 04 - Trabalhando com banco de dados na Magento
    url:   /trabalhando-com-banco-de-dados
  - title: 05 - Utilizando o modelo Entity-Attribute-Value (EAV)
    url:   /utilizando-eav-model
  - title: 06 - Desenvolvendo com o adminhtml
    url:   /desenvolvendo-com-o-adminhtml
  - title: 07 - Personalizando o catálogo
    url:   /personalizando-o-catalogo
  - title: 08 - Personalizando o processo de checkout
    url:   /personalizando-o-checkout
  - title: 09 - Operações de vendas
    url:   /operacoes-de-vendas
  - title: 10 - Gestão de clientes
    url:   /gestao-de-clientes

no_search: false
accent_image: none
accent_color: rgb(25, 110, 27)
